# Pytorch
Pytorch is an open source deep learning framework for building deep learning models. It is used for common applications like image recognition, natural language processing, etc.

Let's import PyTorch library before going any further.

In [ ]:
import torch

# Tensor
Tensor is basically same as a numpy array. Tensor can be a number, vector, matrix, or n-dimensional array. We can use PyTorch to process tensors easily.

Let's define a number as a tensor.

In [ ]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

Look into the data type of the elements in the `t1` tensor

In [ ]:
t1.dtype

torch.float32

Define a vector as a tensor.

In [ ]:
# Vector
t2 = torch.tensor([1., 2, 5, 4])
t2

tensor([1., 2., 5., 4.])

Define a matrix as a tensor. Here I have selected a 2x2 matrix.

In [ ]:
# Matrix
t3 = torch.tensor([
    [1., 2],
    [5, 4]
])
t3

tensor([[1., 2.],
        [5., 4.]])

Define a 3-dimensional array. Here I have defined a 2x2x2 array.

In [ ]:
# 3-dimensional array
t4 = torch.tensor([
    [
        [1., 2],
        [4, 5]
    ],
    [
        [7, 8.],
        [9, 10]
    ]
])
t4

tensor([[[ 1.,  2.],
         [ 4.,  5.]],

        [[ 7.,  8.],
         [ 9., 10.]]])

Let's take a look into shapes of the tensors `t1`, `t2`, `t3`, `t4`.


In [ ]:
print(t1.shape)
print(t2.shape)
print(t3.shape)
print(t4.shape)

torch.Size([])
torch.Size([4])
torch.Size([2, 2])
torch.Size([2, 2, 2])


I have a question for you. **Can you explain the shape we get for `t1`? 🤔 Any IDEAS!!!**

This has happen due to the way of representing dimensions. `torch.Size([])` is the way to represent the shape or dimension of a scalar tensor. I hope you remember that `t1` is a tensor of a number. If not, you have to scroll up and check yourself🙂.

Excercise:

Add/remove elements from rows and columns in different arrays and check how shape changes.

In [ ]:
# Example
t5 = torch.tensor([
    [1., 2, 3],
    [5, 4, 6]
])
t5

tensor([[1., 2., 3.],
        [5., 4., 6.]])

Check out the shape.

In [ ]:
print(t5.shape)

torch.Size([2, 3])


Now you know how to create tensors. Let's look into diffent tensor operations.

# Tensor Operations
We can use basic arithmetic operations with tensors. Let's create some tensors and dive in.

In [ ]:
# create tensors
x = torch.tensor(3.)
w = torch.tensor(4.)
b = torch.tensor(1.)
x, w, b

(tensor(3.), tensor(4.), tensor(1.))

We can perform arithmetic operations on above tensors as below.

In [ ]:
# perform arithmetic operation
y = w * x + b
y

tensor(13.)

We can find gradients as well. For that we need to define with respective to what we expect to find derivates. You can do that as below.

In [ ]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(1., requires_grad = True)

y = w * x + b

# calculate gradients
y.backward()

You can check the calculated gradients as below.

In [ ]:
print("dy/dx:", x.grad)
print("dy/dw:", w.grad)
print("dy/db:", b.grad)

dy/dx: None
dy/dw: tensor(3.)
dy/db: tensor(1.)


**Why we get `dy/dx` as `None`? 🤔**

It is because we didn't define `requires_grad` to `True` for `x`. That means previously we haven't asked PyTorch to keep track of gradients with respect to `x`

Now let's look into how we can use NumPy arrays to generate tensors.  

# NumPy
NumPy is a package for scientific computing in Python programming language. It adds support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

We can create a NumPy array as below.

In [ ]:
import numpy as np

x = np.array([[1., 2.], [3, 4]])
x

array([[1., 2.],
       [3., 4.]])

You can check the data type of the elements in the NumPy array as below.

In [ ]:
# check data type
x.dtype

dtype('float64')

We can convert a NumPy array into tensor as below.

In [ ]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [ ]:
# check data type
y.dtype

torch.float64

We can convert tensor in to NumPy array as well. Check the below example.

In [ ]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

# Conclusion
In this blog, we checked out PyTorch tensors and what they can do. I hope you followed along well. If you're unsure about anything, just leave a comment. I'll catch you in the next blog, where we'll dive into more cool PyTorch stuff!